[2025-01-05T23:30:04.955+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T23:30:04.968+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ico_scraping_dag_10.store_in_postgres scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-05T23:30:04.976+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ico_scraping_dag_10.store_in_postgres scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-05T23:30:04.977+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-05T23:30:04.988+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): store_in_postgres> on 2025-01-04 00:00:00+00:00
[2025-01-05T23:30:04.997+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ico_scraping_dag_10', 'store_in_postgres', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/selenium_dag_01.py', '--cfg-path', '/tmp/tmpd23l_4v0']
[2025-01-05T23:30:05.000+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask store_in_postgres
[2025-01-05T23:30:05.000+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=868) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-05T23:30:05.001+0000] {standard_task_runner.py:72} INFO - Started process 870 to run task
[2025-01-05T23:30:05.044+0000] {task_command.py:467} INFO - Running <TaskInstance: ico_scraping_dag_10.store_in_postgres scheduled__2025-01-04T00:00:00+00:00 [running]> on host ce52e7e8ec7c
[2025-01-05T23:30:05.109+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ico_scraping_dag_10' AIRFLOW_CTX_TASK_ID='store_in_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-01-05T23:30:05.110+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T23:30:05.149+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 217, in store_in_postgres
    pg_hook.run(create_table_sql)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 494, in run
    with self._create_autocommit_connection(autocommit) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 618, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 157, in get_conn
    conn = deepcopy(self.connection)
                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 212, in connection
    self._connection = self.get_connection(self.get_conn_id())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2025-01-05T23:30:05.153+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ico_scraping_dag_10, task_id=store_in_postgres, run_id=scheduled__2025-01-04T00:00:00+00:00, execution_date=20250104T000000, start_date=20250105T233004, end_date=20250105T233005
[2025-01-05T23:30:05.162+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T23:30:05.163+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task store_in_postgres (The conn_id `postgres_localhost` isn't defined; 870)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 217, in store_in_postgres
    pg_hook.run(create_table_sql)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 494, in run
    with self._create_autocommit_connection(autocommit) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 618, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 157, in get_conn
    conn = deepcopy(self.connection)
                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 212, in connection
    self._connection = self.get_connection(self.get_conn_id())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2025-01-05T23:30:05.176+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-05T23:30:05.189+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T23:30:05.190+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-05T23:44:32.014+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T23:44:32.030+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ico_scraping_dag_10.store_in_postgres scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-05T23:44:32.040+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ico_scraping_dag_10.store_in_postgres scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-01-05T23:44:32.041+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2025-01-05T23:44:32.053+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): store_in_postgres> on 2025-01-04 00:00:00+00:00
[2025-01-05T23:44:32.061+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ico_scraping_dag_10', 'store_in_postgres', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/selenium_dag_01.py', '--cfg-path', '/tmp/tmpm8lfaq0c']
[2025-01-05T23:44:32.065+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask store_in_postgres
[2025-01-05T23:44:32.065+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=391) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-05T23:44:32.065+0000] {standard_task_runner.py:72} INFO - Started process 393 to run task
[2025-01-05T23:44:32.108+0000] {task_command.py:467} INFO - Running <TaskInstance: ico_scraping_dag_10.store_in_postgres scheduled__2025-01-04T00:00:00+00:00 [running]> on host 683fc0486ec4
[2025-01-05T23:44:32.178+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ico_scraping_dag_10' AIRFLOW_CTX_TASK_ID='store_in_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-01-05T23:44:32.179+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T23:44:32.217+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-05T23:44:32.222+0000] {sql.py:553} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS test (
        project_name VARCHAR(255),
        project_ticker VARCHAR(50),
        project_link TEXT,
        project_round VARCHAR(100),
        project_total_raised VARCHAR(100),
        project_pre_valuation VARCHAR(100),
        project_categories VARCHAR(255),
        project_roi VARCHAR(100),
        project_date VARCHAR(100),
        project_total_investors INTEGER
    );
    , parameters: None
[2025-01-05T23:44:32.236+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-05T23:44:32.279+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-05T23:44:32.289+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T23:44:32.289+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ico_scraping_dag_10, task_id=store_in_postgres, run_id=scheduled__2025-01-04T00:00:00+00:00, execution_date=20250104T000000, start_date=20250105T234432, end_date=20250105T234432
[2025-01-05T23:44:32.320+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-05T23:44:32.331+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-05T23:44:32.334+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
