[2025-01-05T23:32:19.933+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-05T23:32:19.948+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ico_scraping_dag_10.scrape_ico_data manual__2025-01-05T23:32:16.606423+00:00 [queued]>
[2025-01-05T23:32:19.955+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ico_scraping_dag_10.scrape_ico_data manual__2025-01-05T23:32:16.606423+00:00 [queued]>
[2025-01-05T23:32:19.955+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-05T23:32:19.965+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_ico_data> on 2025-01-05 23:32:16.606423+00:00
[2025-01-05T23:32:19.975+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ico_scraping_dag_10', 'scrape_ico_data', 'manual__2025-01-05T23:32:16.606423+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/selenium_dag_01.py', '--cfg-path', '/tmp/tmpd30mxpnp']
[2025-01-05T23:32:19.979+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask scrape_ico_data
[2025-01-05T23:32:19.979+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=930) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-05T23:32:19.979+0000] {standard_task_runner.py:72} INFO - Started process 932 to run task
[2025-01-05T23:32:20.025+0000] {task_command.py:467} INFO - Running <TaskInstance: ico_scraping_dag_10.scrape_ico_data manual__2025-01-05T23:32:16.606423+00:00 [running]> on host ce52e7e8ec7c
[2025-01-05T23:32:20.098+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ico_scraping_dag_10' AIRFLOW_CTX_TASK_ID='scrape_ico_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T23:32:16.606423+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-05T23:32:16.606423+00:00'
[2025-01-05T23:32:20.099+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-05T23:32:20.112+0000] {logging_mixin.py:190} INFO - Starting the web scraping process...
[2025-01-05T23:32:20.165+0000] {logging_mixin.py:190} INFO - Chrome version: Chromium 114.0.5735.0
[2025-01-05T23:32:20.165+0000] {logging_mixin.py:190} INFO - ChromeDriver version: ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052})
[2025-01-05T23:32:20.166+0000] {logging_mixin.py:190} INFO - Chrome binary location set to: /opt/chrome/chrome
[2025-01-05T23:32:20.167+0000] {logging_mixin.py:190} INFO - ChromeDriver path set to: /opt/chromedriver/chromedriver
[2025-01-05T23:32:20.679+0000] {logging_mixin.py:190} INFO - WebDriver initialized successfully.
[2025-01-05T23:32:20.680+0000] {logging_mixin.py:190} INFO - Navigating to the ICO Drops page...
[2025-01-05T23:32:22.798+0000] {logging_mixin.py:190} INFO - Attempting to click element with xpath: //button[contains(text(), 'Agree')]
[2025-01-05T23:32:22.860+0000] {logging_mixin.py:190} INFO - Element found, clicking on it: //button[contains(text(), 'Agree')]
[2025-01-05T23:32:25.965+0000] {logging_mixin.py:190} INFO - Found 100 ICOs on the page.
[2025-01-05T23:32:25.965+0000] {logging_mixin.py:190} INFO - 
Processing ICO 1/100
[2025-01-05T23:32:25.994+0000] {logging_mixin.py:190} INFO - Extracted project_name: Beam
[2025-01-05T23:32:26.020+0000] {logging_mixin.py:190} INFO - Extracted project_ticker: BEAM
[2025-01-05T23:32:26.048+0000] {logging_mixin.py:190} INFO - Extracted project_link: https://icodrops.com/beam/
[2025-01-05T23:32:26.074+0000] {logging_mixin.py:190} INFO - Extracted project_round: Node Sale Round
[2025-01-05T23:32:26.096+0000] {logging_mixin.py:190} INFO - Extracted project_total_raised: $77.75 M
[2025-01-05T23:32:26.123+0000] {logging_mixin.py:190} INFO - Extracted project_pre_valuation: $1.78 B
[2025-01-05T23:32:26.147+0000] {logging_mixin.py:190} INFO - Extracted project_categories: Gaming
[2025-01-05T23:32:26.175+0000] {logging_mixin.py:190} INFO - Extracted project_roi: 0.01x
[2025-01-05T23:32:26.199+0000] {logging_mixin.py:190} INFO - Extracted project_date: Q4, 2024
[2025-01-05T23:32:26.287+0000] {logging_mixin.py:190} INFO - Extracted project_total_investors: 11
[2025-01-05T23:32:26.287+0000] {logging_mixin.py:190} INFO - 
Processing ICO 2/100
[2025-01-05T23:32:26.312+0000] {logging_mixin.py:190} INFO - Extracted project_name: Sonic
[2025-01-05T23:32:26.337+0000] {logging_mixin.py:190} INFO - Extracted project_ticker: SONIC
[2025-01-05T23:32:26.360+0000] {logging_mixin.py:190} INFO - Extracted project_link: https://icodrops.com/sonic/
[2025-01-05T23:32:26.385+0000] {logging_mixin.py:190} INFO - Extracted project_round: Testnet Incentive Program
[2025-01-05T23:32:26.408+0000] {logging_mixin.py:190} INFO - Extracted project_total_raised: $12 M
[2025-01-05T23:32:26.431+0000] {logging_mixin.py:190} INFO - Extracted project_pre_valuation: $1.17 M
[2025-01-05T23:32:26.458+0000] {logging_mixin.py:190} INFO - Extracted project_categories: Blockchain
[2025-01-05T23:32:26.491+0000] {logging_mixin.py:190} INFO - Extracted project_roi: —
[2025-01-05T23:32:26.518+0000] {logging_mixin.py:190} INFO - Extracted project_date: Jan 6, 2025
[2025-01-05T23:32:26.606+0000] {logging_mixin.py:190} INFO - Extracted project_total_investors: 7
[2025-01-05T23:32:26.606+0000] {logging_mixin.py:190} INFO - 
Processing ICO 3/100
[2025-01-05T23:32:26.630+0000] {logging_mixin.py:190} INFO - Extracted project_name: ArkeFi
[2025-01-05T23:32:26.657+0000] {logging_mixin.py:190} INFO - Extracted project_ticker: RKFI
[2025-01-05T23:32:26.678+0000] {logging_mixin.py:190} INFO - Extracted project_link: https://icodrops.com/arkefi/
[2025-01-05T23:32:26.713+0000] {logging_mixin.py:190} INFO - Extracted project_round: IDO on Poolz
[2025-01-05T23:32:26.744+0000] {logging_mixin.py:190} INFO - Extracted project_total_raised: —
[2025-01-05T23:32:26.770+0000] {logging_mixin.py:190} INFO - Extracted project_pre_valuation: $20 M  
[2025-01-05T23:32:26.795+0000] {logging_mixin.py:190} INFO - Extracted project_categories: Blockchain Service
[2025-01-05T23:32:26.826+0000] {logging_mixin.py:190} INFO - Extracted project_roi: —
[2025-01-05T23:32:26.856+0000] {logging_mixin.py:190} INFO - Extracted project_date: Jan 3, 2025
[2025-01-05T23:32:45.209+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-01-05T23:32:45.210+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-05T23:32:45.211+0000] {process_utils.py:132} INFO - Sending 15 to group 932. PIDs of all processes in the group: [938, 944, 950, 952, 953, 932]
[2025-01-05T23:32:45.211+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 932
[2025-01-05T23:32:45.212+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-05T23:32:45.214+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0da91e4200>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/61b5d13f9ca384e11c14015135e6f443
[2025-01-05T23:32:45.215+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0da91e64e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/61b5d13f9ca384e11c14015135e6f443
[2025-01-05T23:32:45.216+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0da91e65d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/61b5d13f9ca384e11c14015135e6f443
[2025-01-05T23:32:45.254+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 180, in scrape_data
    data = extract_ico_data(driver, i)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 92, in extract_ico_data
    additional = driver.find_element(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 770, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 382, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-01-05T23:32:45.263+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ico_scraping_dag_10, task_id=scrape_ico_data, run_id=manual__2025-01-05T23:32:16.606423+00:00, execution_date=20250105T233216, start_date=20250105T233219, end_date=20250105T233245
[2025-01-05T23:32:45.272+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-05T23:32:45.304+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=944, status='terminated', started='23:32:19') (944) terminated with exit code None
[2025-01-05T23:32:45.305+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=952, status='terminated', started='23:32:19') (952) terminated with exit code None
[2025-01-05T23:32:45.305+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=950, status='terminated', started='23:32:19') (950) terminated with exit code None
[2025-01-05T23:32:45.305+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=938, status='terminated', started='23:32:19') (938) terminated with exit code None
[2025-01-05T23:32:45.305+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=953, status='terminated', started='23:32:19') (953) terminated with exit code None
[2025-01-05T23:32:45.306+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=932, status='terminated', exitcode=2, started='23:32:19') (932) terminated with exit code 2
