[2025-01-07T00:49:50.554+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-07T00:49:50.567+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ico_scraping_dag_l331.scrape_ico_data manual__2025-01-07T00:49:49.664638+00:00 [queued]>
[2025-01-07T00:49:50.574+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ico_scraping_dag_l331.scrape_ico_data manual__2025-01-07T00:49:49.664638+00:00 [queued]>
[2025-01-07T00:49:50.574+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-07T00:49:50.586+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_ico_data> on 2025-01-07 00:49:49.664638+00:00
[2025-01-07T00:49:50.595+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ico_scraping_dag_l331', 'scrape_ico_data', 'manual__2025-01-07T00:49:49.664638+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/selenium_dag_01.py', '--cfg-path', '/tmp/tmpp1aa6xwy']
[2025-01-07T00:49:50.599+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1517) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-07T00:49:50.599+0000] {standard_task_runner.py:72} INFO - Started process 1519 to run task
[2025-01-07T00:49:50.599+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask scrape_ico_data
[2025-01-07T00:49:50.642+0000] {task_command.py:467} INFO - Running <TaskInstance: ico_scraping_dag_l331.scrape_ico_data manual__2025-01-07T00:49:49.664638+00:00 [running]> on host e0f05d443e24
[2025-01-07T00:49:50.711+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ico_scraping_dag_l331' AIRFLOW_CTX_TASK_ID='scrape_ico_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T00:49:49.664638+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T00:49:49.664638+00:00'
[2025-01-07T00:49:50.712+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-07T00:49:50.725+0000] {logging_mixin.py:190} INFO - Starting the web scraping process...
[2025-01-07T00:49:50.753+0000] {logging_mixin.py:190} INFO - Chrome version: Chromium 114.0.5735.0
[2025-01-07T00:49:50.753+0000] {logging_mixin.py:190} INFO - ChromeDriver version: ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052})
[2025-01-07T00:49:50.753+0000] {logging_mixin.py:190} INFO - Chrome binary location set to: /opt/chrome/chrome
[2025-01-07T00:49:50.755+0000] {logging_mixin.py:190} INFO - ChromeDriver path set to: /opt/chromedriver/chromedriver
[2025-01-07T00:49:50.886+0000] {logging_mixin.py:190} INFO - WebDriver initialized successfully.
[2025-01-07T00:49:50.887+0000] {logging_mixin.py:190} INFO - Navigating to the ICO Drops page...
[2025-01-07T00:49:52.688+0000] {logging_mixin.py:190} INFO - Attempting to click element with xpath: //button[contains(text(), 'Agree')]
[2025-01-07T00:49:52.737+0000] {logging_mixin.py:190} INFO - Element found, clicking on it: //button[contains(text(), 'Agree')]
[2025-01-07T00:49:55.827+0000] {logging_mixin.py:190} INFO - Found 100 ICOs on the page.
[2025-01-07T00:49:55.827+0000] {logging_mixin.py:190} INFO - 
Processing ICO 1/100
[2025-01-07T00:49:55.858+0000] {logging_mixin.py:190} INFO - Extracted project_name: Beam
[2025-01-07T00:49:55.879+0000] {logging_mixin.py:190} INFO - Extracted project_ticker: BEAM
[2025-01-07T00:49:55.903+0000] {logging_mixin.py:190} INFO - Extracted project_link: https://icodrops.com/beam/
[2025-01-07T00:49:55.939+0000] {logging_mixin.py:190} INFO - Extracted project_round: Node Sale Round
[2025-01-07T00:49:55.974+0000] {logging_mixin.py:190} INFO - Extracted project_total_raised: $77.75 M
[2025-01-07T00:49:56.010+0000] {logging_mixin.py:190} INFO - Extracted project_pre_valuation: $1.77 B
[2025-01-07T00:49:56.056+0000] {logging_mixin.py:190} INFO - Extracted project_categories: Gaming
[2025-01-07T00:49:56.080+0000] {logging_mixin.py:190} INFO - Extracted project_roi: 0.01x
[2025-01-07T00:49:56.100+0000] {logging_mixin.py:190} INFO - Extracted project_date: Q4, 2024
[2025-01-07T00:49:56.158+0000] {logging_mixin.py:190} INFO - Extracted project_total_investors: 11
[2025-01-07T00:49:56.158+0000] {logging_mixin.py:190} INFO - 
Processing ICO 2/100
[2025-01-07T00:49:56.180+0000] {logging_mixin.py:190} INFO - Extracted project_name: aiPump
[2025-01-07T00:49:56.201+0000] {logging_mixin.py:190} INFO - Extracted project_ticker: AIPUMP
[2025-01-07T00:49:56.227+0000] {logging_mixin.py:190} INFO - Extracted project_link: https://icodrops.com/aipump/
[2025-01-07T00:49:56.246+0000] {logging_mixin.py:190} INFO - Extracted project_round: IDO on Polkastarter
[2025-01-07T00:49:56.266+0000] {logging_mixin.py:190} INFO - Extracted project_total_raised: —
[2025-01-07T00:49:56.284+0000] {logging_mixin.py:190} INFO - Extracted project_pre_valuation: $6 M  
[2025-01-07T00:49:56.305+0000] {logging_mixin.py:190} INFO - Extracted project_categories: AI Agents
[2025-01-07T00:49:56.324+0000] {logging_mixin.py:190} INFO - Extracted project_roi: —
[2025-01-07T00:49:56.344+0000] {logging_mixin.py:190} INFO - Extracted project_date: in 15h
[2025-01-07T00:50:19.366+0000] {logging_mixin.py:190} INFO - Extracted project_total_investors: 0
[2025-01-07T00:50:19.367+0000] {logging_mixin.py:190} INFO - 
Processing ICO 3/100
[2025-01-07T00:50:19.389+0000] {logging_mixin.py:190} INFO - Extracted project_name: Zephyr
[2025-01-07T00:50:19.409+0000] {logging_mixin.py:190} INFO - Extracted project_ticker: ZEFY
[2025-01-07T00:50:19.426+0000] {logging_mixin.py:190} INFO - Extracted project_link: https://icodrops.com/zephyr/
[2025-01-07T00:50:19.444+0000] {logging_mixin.py:190} INFO - Extracted project_round: Public Sale
[2025-01-07T00:50:19.484+0000] {logging_mixin.py:190} INFO - Extracted project_total_raised: $561 K
[2025-01-07T00:50:19.508+0000] {logging_mixin.py:190} INFO - Extracted project_pre_valuation: $5.5 M  
[2025-01-07T00:50:19.527+0000] {logging_mixin.py:190} INFO - Extracted project_categories: DeFi
[2025-01-07T00:50:19.550+0000] {logging_mixin.py:190} INFO - Extracted project_roi: —
[2025-01-07T00:50:19.569+0000] {logging_mixin.py:190} INFO - Extracted project_date: Q3, 2024
[2025-01-07T00:50:39.615+0000] {logging_mixin.py:190} INFO - Extracted project_total_investors: 0
[2025-01-07T00:50:39.616+0000] {logging_mixin.py:190} INFO - 
Processing ICO 4/100
[2025-01-07T00:50:39.637+0000] {logging_mixin.py:190} INFO - Extracted project_name: Sonic
[2025-01-07T00:50:39.671+0000] {logging_mixin.py:190} INFO - Extracted project_ticker: SONIC
[2025-01-07T00:50:39.689+0000] {logging_mixin.py:190} INFO - Extracted project_link: https://icodrops.com/sonic/
[2025-01-07T00:50:39.709+0000] {logging_mixin.py:190} INFO - Extracted project_round: Testnet Incentive Program
[2025-01-07T00:50:39.731+0000] {logging_mixin.py:190} INFO - Extracted project_total_raised: $12 M
[2025-01-07T00:50:39.753+0000] {logging_mixin.py:190} INFO - Extracted project_pre_valuation: $1.17 M
[2025-01-07T00:50:39.773+0000] {logging_mixin.py:190} INFO - Extracted project_categories: Blockchain
[2025-01-07T00:50:39.797+0000] {logging_mixin.py:190} INFO - Extracted project_roi: —
[2025-01-07T00:50:39.816+0000] {logging_mixin.py:190} INFO - Extracted project_date: Jan 6, 2025
[2025-01-07T00:50:39.873+0000] {logging_mixin.py:190} INFO - Extracted project_total_investors: 7
[2025-01-07T00:50:39.873+0000] {logging_mixin.py:190} INFO - 
Processing ICO 5/100
[2025-01-07T00:50:39.892+0000] {logging_mixin.py:190} INFO - Extracted project_name: ArkeFi
[2025-01-07T00:50:39.915+0000] {logging_mixin.py:190} INFO - Extracted project_ticker: RKFI
[2025-01-07T00:50:39.933+0000] {logging_mixin.py:190} INFO - Extracted project_link: https://icodrops.com/arkefi/
[2025-01-07T00:50:39.953+0000] {logging_mixin.py:190} INFO - Extracted project_round: IDO on Poolz
[2025-01-07T00:50:39.972+0000] {logging_mixin.py:190} INFO - Extracted project_total_raised: —
[2025-01-07T00:50:39.991+0000] {logging_mixin.py:190} INFO - Extracted project_pre_valuation: $20 M  
[2025-01-07T00:50:40.010+0000] {logging_mixin.py:190} INFO - Extracted project_categories: Blockchain Service
[2025-01-07T00:50:40.030+0000] {logging_mixin.py:190} INFO - Extracted project_roi: —
[2025-01-07T00:50:40.049+0000] {logging_mixin.py:190} INFO - Extracted project_date: Jan 3, 2025
[2025-01-07T00:51:02.697+0000] {logging_mixin.py:190} INFO - Extracted project_total_investors: 0
[2025-01-07T00:51:02.699+0000] {logging_mixin.py:190} INFO - 
Processing ICO 6/100
[2025-01-07T00:51:02.718+0000] {logging_mixin.py:190} INFO - Extracted project_name: BIO Protocol
[2025-01-07T00:51:02.735+0000] {logging_mixin.py:190} INFO - Extracted project_ticker: BIO
[2025-01-07T00:51:02.750+0000] {logging_mixin.py:190} INFO - Extracted project_link: https://icodrops.com/bio-protocol/
[2025-01-07T00:51:02.767+0000] {logging_mixin.py:190} INFO - Extracted project_round: Binance Launchpool
[2025-01-07T00:51:02.784+0000] {logging_mixin.py:190} INFO - Extracted project_total_raised: $29.9 M
[2025-01-07T00:51:02.800+0000] {logging_mixin.py:190} INFO - Extracted project_pre_valuation: $2.38 B
[2025-01-07T00:51:02.816+0000] {logging_mixin.py:190} INFO - Extracted project_categories: DeSci
[2025-01-07T00:51:02.832+0000] {logging_mixin.py:190} INFO - Extracted project_roi: 10.81x
[2025-01-07T00:51:02.862+0000] {logging_mixin.py:190} INFO - Extracted project_date: Dec 24, 2024
[2025-01-07T00:51:12.940+0000] {logging_mixin.py:190} INFO - Extracted project_total_investors: 3
[2025-01-07T00:51:12.940+0000] {logging_mixin.py:190} INFO - 
Processing ICO 7/100
[2025-01-07T00:51:12.958+0000] {logging_mixin.py:190} INFO - Extracted project_name: Pandana
[2025-01-07T00:51:12.982+0000] {logging_mixin.py:190} INFO - Extracted project_ticker: PNDN
[2025-01-07T00:51:13.000+0000] {logging_mixin.py:190} INFO - Extracted project_link: https://icodrops.com/pandana/
[2025-01-07T00:51:13.021+0000] {logging_mixin.py:190} INFO - Extracted project_round: Presale
[2025-01-07T00:51:13.041+0000] {logging_mixin.py:190} INFO - Extracted project_total_raised: $722 K
[2025-01-07T00:51:13.062+0000] {logging_mixin.py:190} INFO - Extracted project_pre_valuation: $24 M  
[2025-01-07T00:51:13.082+0000] {logging_mixin.py:190} INFO - Extracted project_categories: Memecoin
[2025-01-07T00:51:13.100+0000] {logging_mixin.py:190} INFO - Extracted project_roi: —
[2025-01-07T00:51:13.119+0000] {logging_mixin.py:190} INFO - Extracted project_date: Q4, 2024
[2025-01-07T00:51:34.957+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-01-07T00:51:34.959+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-07T00:51:34.962+0000] {process_utils.py:132} INFO - Sending 15 to group 1519. PIDs of all processes in the group: [1525, 1531, 1538, 1539, 1540, 1519]
[2025-01-07T00:51:34.962+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1519
[2025-01-07T00:51:34.963+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-07T00:51:34.964+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f000c0f71a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1c6ee1406afd1b7ff0dedbd78367a08f
[2025-01-07T00:51:34.965+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f000c2bf7a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1c6ee1406afd1b7ff0dedbd78367a08f
[2025-01-07T00:51:34.966+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f000c0f48f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1c6ee1406afd1b7ff0dedbd78367a08f
[2025-01-07T00:51:35.008+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 175, in scrape_data
    data = extract_ico_data(driver, i)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 87, in extract_ico_data
    additional = driver.find_element(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 770, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 382, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-01-07T00:51:35.014+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1525, status='terminated', started='00:49:50') (1525) terminated with exit code None
[2025-01-07T00:51:35.015+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1531, status='terminated', started='00:49:50') (1531) terminated with exit code None
[2025-01-07T00:51:35.015+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1538, status='terminated', started='00:49:50') (1538) terminated with exit code None
[2025-01-07T00:51:35.015+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1539, status='terminated', started='00:49:50') (1539) terminated with exit code None
[2025-01-07T00:51:35.016+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1540, status='terminated', started='00:49:50') (1540) terminated with exit code None
[2025-01-07T00:51:35.016+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ico_scraping_dag_l331, task_id=scrape_ico_data, run_id=manual__2025-01-07T00:49:49.664638+00:00, execution_date=20250107T004949, start_date=20250107T004950, end_date=20250107T005135
[2025-01-07T00:51:35.029+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-07T00:51:35.029+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task scrape_ico_data ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(ico_scraping_dag_l331, scrape_ico_data, manual__2025-01-07T00:49:49.664638+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'scrape_ico_data', 'dag_id': 'ico_scraping_dag_l331', 'run_id': 'manual__2025-01-07T00:49:49.664638+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 1, 7, 0, 49, 50, 567717, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 1, 7, 0, 51, 35, 14832, tzinfo=Timezone('UTC')), 'duration': 104}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1519)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 175, in scrape_data
    data = extract_ico_data(driver, i)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 87, in extract_ico_data
    additional = driver.find_element(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 770, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 382, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(ico_scraping_dag_l331, scrape_ico_data, manual__2025-01-07T00:49:49.664638+00:00, -1) is not present in table "task_instance".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 327, in _run_raw_task
    ti.handle_failure(e, test_mode, context, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3428, in handle_failure
    _handle_failure(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1243, in _handle_failure
    TaskInstance.save_to_db(failure_context["ti"], session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3400, in save_to_db
    session.flush()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(ico_scraping_dag_l331, scrape_ico_data, manual__2025-01-07T00:49:49.664638+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'scrape_ico_data', 'dag_id': 'ico_scraping_dag_l331', 'run_id': 'manual__2025-01-07T00:49:49.664638+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 1, 7, 0, 49, 50, 567717, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 1, 7, 0, 51, 35, 14832, tzinfo=Timezone('UTC')), 'duration': 104}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2025-01-07T00:51:35.068+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1519, status='terminated', exitcode=1, started='00:49:50') (1519) terminated with exit code 1
